apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app
  namespace: poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      containers:
        - name: poc-app
          image: ghcr.io/samperay/cicd-poc-app:e1c487167e8c6fb472d1094ee7a826e9d86d5577
          ports:
            - containerPort: 8080
