apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app
  namespace: poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      containers:
        - name: poc-app
          image: ghcr.io/<YOUR_GH_ORG_OR_USER>/demo-ci:initial
          ports:
            - containerPort: 8080
